




.build/uno/src/accu_valve_cntrl.cpp : src/accu_valve_cntrl.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/accu_valve_cntrl.ino[0m
	@/home/local/FMCNET/allenma/bin/ino preproc  -o $@ $^


all : .build/uno/src/accu_valve_cntrl.cpp
	@true

