


















.build/uno/Adafruit_TFTLCD/examples/tftpaint_shield/glcdfont.o : lib/Adafruit_TFTLCD/examples/tftpaint_shield/glcdfont.c
	@echo [93mAdafruit_TFTLCD/examples/tftpaint_shield/glcdfont.c[0m
	@mkdir -p .build/uno/Adafruit_TFTLCD/examples/tftpaint_shield
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c lib/Adafruit_TFTLCD/examples/tftpaint_shield/glcdfont.c
include .build/uno/Adafruit_TFTLCD/examples/tftpaint_shield/glcdfont.d






.build/uno/Adafruit_TFTLCD/Adafruit_TFTLCD.o : lib/Adafruit_TFTLCD/Adafruit_TFTLCD.cpp
	@echo [93mAdafruit_TFTLCD/Adafruit_TFTLCD.cpp[0m
	@mkdir -p .build/uno/Adafruit_TFTLCD
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/Adafruit_TFTLCD/Adafruit_TFTLCD.cpp
include .build/uno/Adafruit_TFTLCD/Adafruit_TFTLCD.d



.build/uno/Adafruit_TFTLCD/libAdafruit_TFTLCD.a : .build/uno/Adafruit_TFTLCD/examples/tftpaint_shield/glcdfont.o .build/uno/Adafruit_TFTLCD/Adafruit_TFTLCD.o
	@echo [92mLinking libAdafruit_TFTLCD.a[0m
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/uno/TouchScreen/TouchScreen.o : lib/TouchScreen/TouchScreen.cpp
	@echo [93mTouchScreen/TouchScreen.cpp[0m
	@mkdir -p .build/uno/TouchScreen
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/TouchScreen/TouchScreen.cpp
include .build/uno/TouchScreen/TouchScreen.d



.build/uno/TouchScreen/libTouchScreen.a : .build/uno/TouchScreen/TouchScreen.o
	@echo [92mLinking libTouchScreen.a[0m
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/uno/Adafruit-GFX/glcdfont.o : lib/Adafruit-GFX/glcdfont.c
	@echo [93mAdafruit-GFX/glcdfont.c[0m
	@mkdir -p .build/uno/Adafruit-GFX
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c lib/Adafruit-GFX/glcdfont.c
include .build/uno/Adafruit-GFX/glcdfont.d






.build/uno/Adafruit-GFX/Adafruit_GFX.o : lib/Adafruit-GFX/Adafruit_GFX.cpp
	@echo [93mAdafruit-GFX/Adafruit_GFX.cpp[0m
	@mkdir -p .build/uno/Adafruit-GFX
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/Adafruit-GFX/Adafruit_GFX.cpp
include .build/uno/Adafruit-GFX/Adafruit_GFX.d



.build/uno/Adafruit-GFX/libAdafruit-GFX.a : .build/uno/Adafruit-GFX/glcdfont.o .build/uno/Adafruit-GFX/Adafruit_GFX.o
	@echo [92mLinking libAdafruit-GFX.a[0m
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/uno/arduino/WInterrupts.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
include .build/uno/arduino/WInterrupts.d

.build/uno/arduino/wiring_digital.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
include .build/uno/arduino/wiring_digital.d

.build/uno/arduino/wiring_pulse.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
include .build/uno/arduino/wiring_pulse.d

.build/uno/arduino/wiring.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
include .build/uno/arduino/wiring.d

.build/uno/arduino/wiring_analog.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
include .build/uno/arduino/wiring_analog.d

.build/uno/arduino/hooks.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
	@echo [93marduino/hooks.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
include .build/uno/arduino/hooks.d

.build/uno/arduino/wiring_shift.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
include .build/uno/arduino/wiring_shift.d






.build/uno/arduino/HardwareSerial.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
include .build/uno/arduino/HardwareSerial.d

.build/uno/arduino/WMath.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
include .build/uno/arduino/WMath.d

.build/uno/arduino/HardwareSerial1.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
	@echo [93marduino/HardwareSerial1.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
include .build/uno/arduino/HardwareSerial1.d

.build/uno/arduino/abi.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
	@echo [93marduino/abi.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
include .build/uno/arduino/abi.d

.build/uno/arduino/main.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
include .build/uno/arduino/main.d

.build/uno/arduino/IPAddress.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
include .build/uno/arduino/IPAddress.d

.build/uno/arduino/HardwareSerial3.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
	@echo [93marduino/HardwareSerial3.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
include .build/uno/arduino/HardwareSerial3.d

.build/uno/arduino/Print.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
include .build/uno/arduino/Print.d

.build/uno/arduino/HID.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp
include .build/uno/arduino/HID.d

.build/uno/arduino/USBCore.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
include .build/uno/arduino/USBCore.d

.build/uno/arduino/HardwareSerial2.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
	@echo [93marduino/HardwareSerial2.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
include .build/uno/arduino/HardwareSerial2.d

.build/uno/arduino/HardwareSerial0.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
	@echo [93marduino/HardwareSerial0.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
include .build/uno/arduino/HardwareSerial0.d

.build/uno/arduino/new.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
include .build/uno/arduino/new.d

.build/uno/arduino/WString.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
include .build/uno/arduino/WString.d

.build/uno/arduino/Stream.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
include .build/uno/arduino/Stream.d

.build/uno/arduino/Tone.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
include .build/uno/arduino/Tone.d

.build/uno/arduino/CDC.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
include .build/uno/arduino/CDC.d



.build/uno/arduino/libarduino.a : .build/uno/arduino/WInterrupts.o .build/uno/arduino/wiring_digital.o .build/uno/arduino/wiring_pulse.o .build/uno/arduino/wiring.o .build/uno/arduino/wiring_analog.o .build/uno/arduino/hooks.o .build/uno/arduino/wiring_shift.o .build/uno/arduino/HardwareSerial.o .build/uno/arduino/WMath.o .build/uno/arduino/HardwareSerial1.o .build/uno/arduino/abi.o .build/uno/arduino/main.o .build/uno/arduino/IPAddress.o .build/uno/arduino/HardwareSerial3.o .build/uno/arduino/Print.o .build/uno/arduino/HID.o .build/uno/arduino/USBCore.o .build/uno/arduino/HardwareSerial2.o .build/uno/arduino/HardwareSerial0.o .build/uno/arduino/new.o .build/uno/arduino/WString.o .build/uno/arduino/Stream.o .build/uno/arduino/Tone.o .build/uno/arduino/CDC.o
	@echo [92mLinking libarduino.a[0m
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build/uno/src/tftpaint_shield.o : .build/uno/src/tftpaint_shield.cpp
	@echo [93msrc/tftpaint_shield.cpp[0m
	@mkdir -p .build/uno/src
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=160 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -Ilib/Adafruit_TFTLCD -Ilib/Adafruit_TFTLCD/bitmaps -Ilib/TouchScreen -Ilib/Adafruit-GFX -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions -iquote src  -o $@ -c .build/uno/src/tftpaint_shield.cpp
include .build/uno/src/tftpaint_shield.d







.build/uno/firmware.elf : .build/uno/src/tftpaint_shield.o .build/uno/Adafruit_TFTLCD/libAdafruit_TFTLCD.a .build/uno/TouchScreen/libTouchScreen.a .build/uno/Adafruit-GFX/libAdafruit-GFX.a .build/uno/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/uno/firmware.hex : .build/uno/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/uno/src/dependencies.d .build/uno/Adafruit_TFTLCD/dependencies.d .build/uno/Adafruit-GFX/dependencies.d .build/uno/TouchScreen/dependencies.d .build/uno/arduino/dependencies.d

all : .build/uno/firmware.hex
	@true

