




.build/uno/src/tftpaint_shield.cpp : src/tftpaint_shield.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/tftpaint_shield.ino[0m
	@/home/local/FMCNET/allenma/bin/ino preproc  -o $@ $^


all : .build/uno/src/tftpaint_shield.cpp
	@true

