




.build/uno/src/webserver.cpp : src/webserver.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/webserver.ino[0m
	@/home/local/FMCNET/allenma/bin/ino preproc  -o $@ $^


all : .build/uno/src/webserver.cpp
	@true

