




.build/uno/src/garden.cpp : src/garden.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/garden.ino[0m
	@/home/local/FMCNET/allenma/bin/ino preproc  -o $@ $^


all : .build/uno/src/garden.cpp
	@true

