




.build/uno/src/touchScreen.cpp : src/touchScreen.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/touchScreen.ino[0m
	@/home/local/FMCNET/allenma/bin/ino preproc  -o $@ $^


all : .build/uno/src/touchScreen.cpp
	@true

